---
- hosts: 172.31.10.3
  become: yes
  tasks: 
     - include_tasks: myfilehandle.yml

     - name: i want to installapcahe2
       apt:
          name: apache2
       notify: restartwebserver

     - name: i want to replace apcahe2 template with mypage
       template:
         src: myapache2.j2
         dest: /var/www/html/index.html


  handlers:
     - name: restartwebserver
       service:
          name: apache2
          state: restarted 
