---
- hosts: 172.31.10.3
  become: yes
  tasks:
      - name: i want to run linux cmnd on ubutnu node
        command: hostname -f
        register: myresult

      - name: i want to display the result of linux command
        debug:
           msg: "{{myresult}}"